#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 09.02.19
 * Time: 13:16
 */


require_once __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
$app = new Application();
$app->add(new \alexsisukin\PromoPult\Command\Mail());
$app->add(new \alexsisukin\PromoPult\Command\Regex());
$app -> run();